name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE_NAME: ${{ github.repository_owner }}/brainbridge-backend
  NGINCX_IMAGE_NAME: ${{ github.repository_owner }}/brainbridge-nginx

jobs:
  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Convert image names to lowercase
        run: |
          echo "BACKEND_IMAGE_NAME=${{ env.BACKEND_IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_ENV
          echo "NGINX_IMAGE_NAME=${{ env.NGINX_IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME_LC }}:latest
            ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME_LC }}:${{ github.sha }}

      - name: Build and Push Nginx image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./nginx/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.NGINX_IMAGE_NAME_LC }}:latest
            ${{ env.REGISTRY }}/${{ env.NGINX_IMAGE_NAME_LC }}:${{ github.sha }}
